# Dependencies
markdown:         kramdown

# Setup
author:
  name:           "Openstax"
  url:            http://cnx.org


title:            "Openstax Economics"

# Custom vars
version:          10.1
origin:           http://cnx.org/contents/69619d2b-68f0-44b0-b074-a9b2bf90b2c6@10.1

bookviewer:       http://philschatz.com/book-viewer
