
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Economics'
tagline:          'from http://cnx.org/contents/69619d2b-68f0-44b0-b074-a9b2bf90b2c6@11.346 (CC-BY)'
url:              https://github.com/philschatz/economics-book
origin:           http://cnx.org/contents/69619d2b-68f0-44b0-b074-a9b2bf90b2c6@11.346

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          11.346

bookviewer:       http://philschatz.com/book-viewer

